language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
os:
- linux
- osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: OWH6vNM8UpKjFJ2QST43cFs5MGOkh9icCs+8hfq/qjRIFph4dbxFKWvyGtfyc5yfMgaZ1w73f9uLGMsMFRERHW4pPSt+6KMBoFtRaESJiAWcEUch75zHvFZ5+dlkvvWHKBNiQslmDD4BkRfzNufoep2xtphjdp5uMo2Dnf+QpLfqbc2C6T2IKUJiXhku64Lwky+vtBjaDTFWMkP5mBRRCDHR3x/UtdD6V3A3n0sW2hogt+f0KfVBIfYE6gtz9yCrqyNR2bHpzZ547KQMnlR7xR3jBQ7x1b20D222mwuHmV8DdM5apouKKd2IdI0/Nl9NY7U99iX8aiIjPqur7T2BcuJfLT7rSq9fKsh5Ca7m7vKXEj9cyj62IIrxkrbvQnYztPtJNW/Nw+pDPgqh3svwTKwhjIo80soql4uOn3LgHNzlMxecqLTwSfRdfUe8kr7Aj8PTcYWguEF128GPW1wV8y1LLXjCBcWYfrxgSAN7oLBQAat1LVNGZPEw560ZKqLY3isKhmkB+f1yszo27E48SBFmrk4B7WsjVx07ITqqW21VwLvetMeXVDVJc2GZ1kRN9CQE7EIDiEiwlx6QYAonRD6jTLLZWNq9qgCB8DANihOJdM3MbGfodV04Aqg9NTPh7+b9zA5hSTS216JIBfVyaz6n48g8R+zvaDBvI2f1SH4=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
