language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: pLYdmkHH9h1aXJ+PUYILRFhXuV6EINDZqMGrXbk3ckfFJPankGzX9B2YA3Tgz5n4F56RmV3MkDmG6tuMtooxCEzMh1ZSy+XzeNuBKFiu4IGVNINpYah5OMk3uJajgnO5j/NYb3T75Ph1MU41MEa9f4F6BSrMd+r9qe6yWcJOaD6OYEAm1bap9z24Z2yFQOhzZcBIo+dslsFVp8tn17cWdxjXOey+FASqj7PlMLW+tPJTR23LqO2fqugTLkHd+r61OnjuCArziBOLapLzop04LVBBcF+cU7S8Qji2iHDJg2P/EEJ7VcQXVyXLWJUDONqIEf4kLKqsdgwtFV3/MKg0r7iWx1gtYbSAZXB8gUrsVis9c/12ZS0dxA4PCBv0LqF4U51iiQZKXQcSkhvC+WM9WCf9d2hi39ijkgtDW2/cHyJ+uK2OoVygsfZXk2//8+8kerlUK9QBt//Qv9L9Y2YdtwptJUGrFUCUWSuPDOBSlsFxmYKFMsFOrmvv8HMuVEdXQnVe24OP8ARNe9wZI53Dln2ARMoHNMDAXeBjjRIPJWpnzfVf5eMkpVvMzSp3upacDz+/vsA8eOnFKEeXMVNKdb2nA+kSrzfUbUoIzSaWfRGog41/b9jFes1aSHIXFOBf2I7qF+9YoS9gY/IUgoNqeXE6+EWn9G23GL4bERGuhn8=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
