language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: LBB3lDb1eDuzbW8suei/usFofOaF26gQgOKxE9+P32iczRqMjS40QTuw/Z7XrA0UCwx+sN0WyQgE4M8PISHZZcXajJBusAv9PXGkYuYCO5uVSEwP42yc1VD6+buZdzPH4apTsSCD2mE/XHpq2Jog33OrjdcrUn8VuXq8frWDnSUISQK366I9p2FLsqrTmqHw6ag/MRE0yNaskznA3Bk1615TYEoBWqVMoaq5/kKjytT0uvOuaS9tlKBbNkVnHiEhdlWsIZFtFcXlj3+e1YSv2mY+VZKh/SLonOxDhELHgjneedyIOib5xUfzHNiKhZkiUjb0N0OWHZGXXFYUwAVwo+gbobCO4HV/1/i7gfC4KQ0L/LtbQgv1YzHts8+TYdZRPP2MQzrXjeQ+Ybo68kcDq0DAQ+zdxqAWUunexDwG6LOCWgIdEJ6P7R/1Vw3fOW2hlp4aSc2tow8y9BYMhSqnqoCbifcwYhegNRheufSQw/EB/7Tz4uNf9+rq7n1WycUSMd1Z7QYcMNO28jDQWQcVCMpIlKPioeK6OMEWLN6JyngbX/TULT9RZzlboLeEk97AmYOaphpzUXTPIFwIDGlBRXMpzPvwzK/8wnhKNeomOf8CBhIJQ+vX93w1NiFWBWRA7fSloyiw6e62LWjXF+fMvWr+10bnjcdYXLNN4DA2cAY=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
